import type {
  PrefabGenerationInput,
  PrefabGenerationResult,
} from "../../types/prefabGenerator";

const EXPECTED_INPUT = {
  assetId: "chair_simple",
  archetypeId: "furniture.chair",
  detailTier: "basic",
  variant: "wooden",
} as const;

const ERGONOMICS_SCALE: Record<string, number> = {
  human_standard: 1.0,
  human_compact: 0.9,
  human_large: 1.1,
};

const DESTINATION_SCALE: Record<string, number> = {
  neutral: 1.0,
  meters: 1.0,
  centimeters: 100.0,
};

const BASE_DIMENSIONS_METERS = {
  seatWidth: 0.45,
  seatDepth: 0.45,
  seatThickness: 0.05,
  seatHeight: 0.45,
  legRadius: 0.02,
  legHeight: 0.45,
  backWidth: 0.45,
  backHeight: 0.5,
  backThickness: 0.04,
} as const;

type GeneratedChairDimensions = {
  seatSize: [number, number, number];
  seatLocation: [number, number, number];
  legRadius: number;
  legHeight: number;
  legPositions: Array<[number, number, number]>;
  backSize: [number, number, number];
  backLocation: [number, number, number];
};

const computeDimensions = (
  ergonomicsProfile: string,
  destinationScale: string
): { dimensions: GeneratedChairDimensions; notes: string[] } => {
  const notes: string[] = [];
  const ergonomicsFactor = ERGONOMICS_SCALE[ergonomicsProfile] ?? 1.0;
  if (!ERGONOMICS_SCALE[ergonomicsProfile]) {
    notes.push(
      `Unknown ergonomicsProfile "${ergonomicsProfile}"; using human_standard scale.`
    );
  }

  const destinationFactor = DESTINATION_SCALE[destinationScale] ?? 1.0;
  if (!DESTINATION_SCALE[destinationScale]) {
    notes.push(
      `Unknown destinationScale "${destinationScale}"; using neutral scale.`
    );
  }

  const scale = ergonomicsFactor * destinationFactor;

  const seatSize: [number, number, number] = [
    BASE_DIMENSIONS_METERS.seatWidth * scale,
    BASE_DIMENSIONS_METERS.seatDepth * scale,
    BASE_DIMENSIONS_METERS.seatThickness * scale,
  ];

  const seatLocation: [number, number, number] = [
    0,
    0,
    (BASE_DIMENSIONS_METERS.seatHeight + BASE_DIMENSIONS_METERS.seatThickness / 2) *
      scale,
  ];

  const legRadius = BASE_DIMENSIONS_METERS.legRadius * scale;
  const legHeight = BASE_DIMENSIONS_METERS.legHeight * scale;

  const halfSeatX = (BASE_DIMENSIONS_METERS.seatWidth / 2 - legRadius) * scale;
  const halfSeatY = (BASE_DIMENSIONS_METERS.seatDepth / 2 - legRadius) * scale;
  const legZ = (BASE_DIMENSIONS_METERS.legHeight / 2) * scale;

  const legPositions: Array<[number, number, number]> = [
    [halfSeatX, halfSeatY, legZ],
    [halfSeatX, -halfSeatY, legZ],
    [-halfSeatX, halfSeatY, legZ],
    [-halfSeatX, -halfSeatY, legZ],
  ];

  const backSize: [number, number, number] = [
    BASE_DIMENSIONS_METERS.backWidth * scale,
    BASE_DIMENSIONS_METERS.backThickness * scale,
    BASE_DIMENSIONS_METERS.backHeight * scale,
  ];

  const backLocation: [number, number, number] = [
    0,
    (-BASE_DIMENSIONS_METERS.seatDepth / 2 + BASE_DIMENSIONS_METERS.backThickness / 2) *
      scale,
    (BASE_DIMENSIONS_METERS.seatHeight + BASE_DIMENSIONS_METERS.backHeight / 2) * scale,
  ];

  return {
    dimensions: {
      seatSize,
      seatLocation,
      legRadius,
      legHeight,
      legPositions,
      backSize,
      backLocation,
    },
    notes,
  };
};

const buildBlenderPythonScript = (dimensions: GeneratedChairDimensions): string => {
  const seatSize = dimensions.seatSize.join(", ");
  const seatLocation = dimensions.seatLocation.join(", ");
  const backSize = dimensions.backSize.join(", ");
  const backLocation = dimensions.backLocation.join(", ");

  const legScripts = dimensions.legPositions
    .map((position, index) => {
      const location = position.join(", ");
      return `
bpy.ops.mesh.primitive_cylinder_add(
  radius=${dimensions.legRadius},
  depth=${dimensions.legHeight},
  location=(${location})
)
bpy.context.active_object.name = "chair_leg_${index + 1}"
`;
    })
    .join("\n");

  return `
import bpy

# Generated by prefab generator: chair_basic_wooden
# No modifiers, no materials, no file output.

bpy.ops.mesh.primitive_cube_add(size=1, location=(${seatLocation}))
seat = bpy.context.active_object
seat.name = "chair_seat"
seat.scale = (${seatSize})

${legScripts}

bpy.ops.mesh.primitive_cube_add(size=1, location=(${backLocation}))
back = bpy.context.active_object
back.name = "chair_back"
back.scale = (${backSize})
`.trim();
};

export const generateChairBasicWooden = (
  input: PrefabGenerationInput
): PrefabGenerationResult => {
  if (input.assetId !== EXPECTED_INPUT.assetId) {
    return {
      ok: false,
      prefabKey: input.prefabKey,
      error: {
        code: "INVALID_ASSET_ID",
        message: `Unsupported assetId: ${input.assetId}.`,
        details: [`Expected ${EXPECTED_INPUT.assetId}.`],
      },
    };
  }

  if (input.archetypeId !== EXPECTED_INPUT.archetypeId) {
    return {
      ok: false,
      prefabKey: input.prefabKey,
      error: {
        code: "INVALID_ARCHETYPE_ID",
        message: `Unsupported archetypeId: ${input.archetypeId}.`,
        details: [`Expected ${EXPECTED_INPUT.archetypeId}.`],
      },
    };
  }

  if (input.detailTier !== EXPECTED_INPUT.detailTier) {
    return {
      ok: false,
      prefabKey: input.prefabKey,
      error: {
        code: "INVALID_DETAIL_TIER",
        message: `Unsupported detailTier: ${input.detailTier}.`,
        details: [`Expected ${EXPECTED_INPUT.detailTier}.`],
      },
    };
  }

  if (input.variant !== EXPECTED_INPUT.variant) {
    return {
      ok: false,
      prefabKey: input.prefabKey,
      error: {
        code: "INVALID_VARIANT",
        message: `Unsupported variant: ${input.variant}.`,
        details: [`Expected ${EXPECTED_INPUT.variant}.`],
      },
    };
  }

  const { dimensions, notes: scaleNotes } = computeDimensions(
    input.ergonomicsProfile,
    input.destinationScale
  );

  const pythonScript = buildBlenderPythonScript(dimensions);

  return {
    ok: true,
    prefabKey: input.prefabKey,
    created: {
      summary:
        "Generated symbolic chair geometry (seat, four legs, back) using Blender primitives.",
      artefactIds: [
        "chair_seat",
        "chair_leg_1",
        "chair_leg_2",
        "chair_leg_3",
        "chair_leg_4",
        "chair_back",
      ],
      notes: [
        "Assumes human-scale baseline with proportional adjustments from ergonomicsProfile.",
        "No modifiers, materials, or file output; geometry is purely demonstrative.",
        ...scaleNotes,
      ],
      scripts: {
        blenderPython: pythonScript,
      },
    },
  };
};
