import type {
  PrefabGenerationInput,
  PrefabGenerationResult,
} from "../../types/prefabGenerator";

const EXPECTED_INPUT = {
  assetId: "table_simple",
  archetypeId: "furniture.table",
  detailTier: "basic",
  variant: "wooden",
} as const;

const ERGONOMICS_SCALE: Record<string, number> = {
  human_standard: 1.0,
  human_compact: 0.9,
  human_large: 1.1,
};

const DESTINATION_SCALE: Record<string, number> = {
  neutral: 1.0,
  meters: 1.0,
  centimeters: 100.0,
};

// Base dimensions in meters for a simple, human-scale table.
const BASE_DIMENSIONS_METERS = {
  topWidth: 1.2,
  topDepth: 0.75,
  topThickness: 0.05,
  topHeight: 0.75,
  legRadius: 0.03,
  legHeight: 0.75,
} as const;

type GeneratedTableDimensions = {
  topSize: [number, number, number];
  topLocation: [number, number, number];
  legRadius: number;
  legHeight: number;
  legPositions: Array<[number, number, number]>;
};

const computeDimensions = (
  ergonomicsProfile: string,
  destinationScale: string
): { dimensions: GeneratedTableDimensions; notes: string[] } => {
  const notes: string[] = [];
  const ergonomicsFactor = ERGONOMICS_SCALE[ergonomicsProfile] ?? 1.0;
  if (!ERGONOMICS_SCALE[ergonomicsProfile]) {
    notes.push(
      `Unknown ergonomicsProfile "${ergonomicsProfile}"; using human_standard scale.`
    );
  }

  const destinationFactor = DESTINATION_SCALE[destinationScale] ?? 1.0;
  if (!DESTINATION_SCALE[destinationScale]) {
    notes.push(
      `Unknown destinationScale "${destinationScale}"; using neutral scale.`
    );
  }

  const scale = ergonomicsFactor * destinationFactor;

  const topSize: [number, number, number] = [
    BASE_DIMENSIONS_METERS.topWidth * scale,
    BASE_DIMENSIONS_METERS.topDepth * scale,
    BASE_DIMENSIONS_METERS.topThickness * scale,
  ];

  const topLocation: [number, number, number] = [
    0,
    0,
    (BASE_DIMENSIONS_METERS.topHeight + BASE_DIMENSIONS_METERS.topThickness / 2) *
      scale,
  ];

  const legRadius = BASE_DIMENSIONS_METERS.legRadius * scale;
  const legHeight = BASE_DIMENSIONS_METERS.legHeight * scale;

  const halfTopX = (BASE_DIMENSIONS_METERS.topWidth / 2 - legRadius) * scale;
  const halfTopY = (BASE_DIMENSIONS_METERS.topDepth / 2 - legRadius) * scale;
  const legZ = (BASE_DIMENSIONS_METERS.legHeight / 2) * scale;

  const legPositions: Array<[number, number, number]> = [
    [halfTopX, halfTopY, legZ],
    [halfTopX, -halfTopY, legZ],
    [-halfTopX, halfTopY, legZ],
    [-halfTopX, -halfTopY, legZ],
  ];

  return {
    dimensions: {
      topSize,
      topLocation,
      legRadius,
      legHeight,
      legPositions,
    },
    notes,
  };
};

const buildBlenderPythonScript = (dimensions: GeneratedTableDimensions): string => {
  const topSize = dimensions.topSize.join(", ");
  const topLocation = dimensions.topLocation.join(", ");

  const legScripts = dimensions.legPositions
    .map((position, index) => {
      const location = position.join(", ");
      return `
bpy.ops.mesh.primitive_cylinder_add(
  radius=${dimensions.legRadius},
  depth=${dimensions.legHeight},
  location=(${location})
)
bpy.context.active_object.name = "table_leg_${index + 1}"
`;
    })
    .join("\n");

  return `
import bpy

# Generated by prefab generator: table_basic_wooden
# No modifiers, no materials, no file output.

bpy.ops.mesh.primitive_cube_add(size=1, location=(${topLocation}))
top = bpy.context.active_object
top.name = "table_top"
top.scale = (${topSize})

${legScripts}
`.trim();
};

export const generateTableBasicWooden = (
  input: PrefabGenerationInput
): PrefabGenerationResult => {
  if (input.assetId !== EXPECTED_INPUT.assetId) {
    return {
      ok: false,
      prefabKey: input.prefabKey,
      error: {
        code: "INVALID_ASSET_ID",
        message: `Unsupported assetId: ${input.assetId}.`,
        details: [`Expected ${EXPECTED_INPUT.assetId}.`],
      },
    };
  }

  if (input.archetypeId !== EXPECTED_INPUT.archetypeId) {
    return {
      ok: false,
      prefabKey: input.prefabKey,
      error: {
        code: "INVALID_ARCHETYPE_ID",
        message: `Unsupported archetypeId: ${input.archetypeId}.`,
        details: [`Expected ${EXPECTED_INPUT.archetypeId}.`],
      },
    };
  }

  if (input.detailTier !== EXPECTED_INPUT.detailTier) {
    return {
      ok: false,
      prefabKey: input.prefabKey,
      error: {
        code: "INVALID_DETAIL_TIER",
        message: `Unsupported detailTier: ${input.detailTier}.`,
        details: [`Expected ${EXPECTED_INPUT.detailTier}.`],
      },
    };
  }

  if (input.variant !== EXPECTED_INPUT.variant) {
    return {
      ok: false,
      prefabKey: input.prefabKey,
      error: {
        code: "INVALID_VARIANT",
        message: `Unsupported variant: ${input.variant}.`,
        details: [`Expected ${EXPECTED_INPUT.variant}.`],
      },
    };
  }

  const { dimensions, notes: scaleNotes } = computeDimensions(
    input.ergonomicsProfile,
    input.destinationScale
  );

  const pythonScript = buildBlenderPythonScript(dimensions);

  return {
    ok: true,
    prefabKey: input.prefabKey,
    created: {
      summary:
        "Generated symbolic table geometry (tabletop and four legs) using Blender primitives.",
      artefactIds: [
        "table_top",
        "table_leg_1",
        "table_leg_2",
        "table_leg_3",
        "table_leg_4",
      ],
      notes: [
        "Proportions target a simple, human-scale dining table.",
        "No modifiers, materials, or file output; geometry is purely demonstrative.",
        ...scaleNotes,
      ],
      scripts: {
        blenderPython: pythonScript,
      },
    },
  };
};
